##Constants that need to be defined and refered to globally
extends Node

const input_box: PackedScene = preload("uid://bihasri21bdv")

#region ENUMS
enum PLAYER_TYPES {PLAYER, CPU}
enum SIDES {NONE, ##IGNORE FIELD AND TAKE DEFAULT
 ATTACKING,##IS FOR THE PLAYER WHOSE TURN IT IS
 DEFENDING,##IS THE OTHER GUY
 BOTH, ##TAKE IN EVERY SLOT THAT FITS SPECIFIERS
 SOURCE, ##ONLY TAKE IN WHOEVER CALLED EFFECT NO MATTER SIDE
 OTHER ##WHICHEVER SIDE DIDN'T CALL THE EFFECT
}
enum SLOTS {NONE,##Ignore and use the default
 TARGET,##Refers to  pokemon involved in attacks and effects
 ACTIVE,##Refers to the pokemon in the Active Slot
 BENCH,##Refers to pokemon in the bench
 ALL,##Refers to any pokemon in the dedicated side
 REST ##Refers to any pokemon not involves with attacks or effects
}
enum STACKS{HAND, ##CARDS HERE CAN BE PLAYED UNDER THE RIGHT CONDITIONS
  DECK, ##CARDS MUST EITHER BE DRAWN OR TUTORED. ALL CRADS BEGIN HERE
  DISCARD, ##AFTER A CARD IS USED, KO'd OR PAYS FOR ANY DISCARD COSTS
  PLAY, ##ANY CARD THAT ISN'T IN A STACK
  LOST, ##THE LOST ZONE, NOT ANY CARD THAT CANNOT BE RETRIEVED FOR FUTURE USE
  ANY,
  NONE
}
enum STACK_ACT{PLAY,##ALLOWED CARDS CAN BE PLAYED ONTO THE BOARD
	TUTOR, ##ALLOWED CARDS WILL BE SENT TO ANOTHER DESTINATION
	DISCARD, ##ALLOWED CARDS WILL BE SENT TO DISCARD PILE
	LOOK, ##NOT ALLOWED TO INTERACT WITH CARDS
	REORDER, ##REARRANGE CARDS AS NECESSARY
	MIMIC
}
#endregion
